CREATE TABLE f_mfd_history (
    id SERIAL PRIMARY KEY,
    fiber_id VARCHAR(100),
    length NUMERIC,
    measurement_date DATE,
    measurement_time TIME,
    mfd_wavelength_top_1310 NUMERIC,
    gaussian_mfd_top_1310 NUMERIC,
    mfd_1310_top NUMERIC,
    effective_area_1310 NUMERIC,
    mfd_wavelength_bottom_1310 NUMERIC,
    gaussian_mfd_bottom_1310 NUMERIC,
    mfd_1310_bottom NUMERIC,
    effective_area_bottom_1310 NUMERIC,
    mfd_wavelength_top_1550 NUMERIC,
    gaussian_mfd_top_1550 NUMERIC,
    mfd_1550_top NUMERIC,
    effective_area_1550 NUMERIC,
    mfd_wavelength_bottom_1550 NUMERIC,
    gaussian_mfd_bottom_1550 NUMERIC,
    mfd_1550_bottom NUMERIC,
    effective_area_bottom_1550 NUMERIC,
    Operator VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);